# Generated by Django 4.1.2 on 2022-10-06 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mio_auth_user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mio_user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('airline_code', models.CharField(max_length=50)),
                
            ],
        ),
    ]
