# Generated by Django 4.1.2 on 2022-10-06 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mio_user',
            fields=[
                ('fact_guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
