# Generated by Django 4.1.2 on 2022-10-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mio_user',
            old_name='last_name',
            new_name='Last_name',
        ),
        migrations.AlterField(
            model_name='mio_auth_user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mio_user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
