# Generated by Django 4.1.2 on 2022-10-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airport', '0003_rename_last_name_mio_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mio_airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=50)),
                ('flight_code', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('airline_code', 'flight_code')},
            },
        ),
        migrations.AlterField(
            model_name='mio_auth_user',
            name='username',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mio_user',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Airport.mio_auth_user'),
        ),
        migrations.CreateModel(
            name='Mio_terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=50)),
                ('gate', models.CharField(max_length=50)),
                ('gate_status', models.CharField(default='open', max_length=50)),
            ],
            options={
                'unique_together': {('terminal', 'gate')},
            },
        ),
        migrations.CreateModel(
            name='Mio_flight_schedule',
            fields=[
                ('fact_guid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_departure', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('baggage_carousel', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airport.mio_airline')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_flight', to='Airport.mio_airline')),
                ('gate_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_gate', to='Airport.mio_terminal')),
                ('terminal_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_terminal', to='Airport.mio_terminal')),
            ],
        ),
        migrations.AlterField(
            model_name='mio_user',
            name='airline_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airport.mio_airline'),
        ),
    ]
