# Generated by Django 4.1.2 on 2022-10-19 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mio_airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=50)),
                ('flight_code', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('airline_code', 'flight_code')},
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2022, 10, 18, 18, 34, 51, 530868), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('airport_employee', 'airport_employee'), ('airline_employee', 'airline_employee'), ('customer', 'customer')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Mio_terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=50)),
                ('gate', models.CharField(max_length=50)),
                ('gate_status', models.CharField(default='open', max_length=50)),
            ],
            options={
                'unique_together': {('terminal', 'gate')},
            },
        ),
        migrations.CreateModel(
            name='Mio_flight_schedule',
            fields=[
                ('fact_guid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_departure', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('baggage_carousel', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwtapp.mio_airline')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_flight', to='jwtapp.mio_airline')),
                ('gate_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_gate', to='jwtapp.mio_terminal')),
                ('terminal_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_terminal', to='jwtapp.mio_terminal')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='airline_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jwtapp.mio_airline'),
        ),
    ]
