# Generated by Django 4.1.2 on 2022-10-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0002_alter_mio_flight_schedule_terminal_gate_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mio_flight_schedule',
            name='terminal_gate_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_terminal_gate', to='jwtapp.mio_terminal'),
        ),
    ]
