# Generated by Django 4.1.2 on 2022-10-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0002_mio_airline_rename_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('airport_employee', 'airport_employee'), ('airline_employee', 'airline_employee'), ('customer', 'customer'), ('admin', 'admin')], max_length=50, null=True),
        ),
    ]
