# Generated by Django 4.1.2 on 2022-10-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0003_alter_mio_flight_schedule_terminal_gate_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tc',
            new_name='terms_conditions',
        ),
        migrations.AlterField(
            model_name='mio_flight_schedule',
            name='airline_flight_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_flight', to='jwtapp.mio_airline'),
        ),
    ]
