# Generated by Django 4.1.2 on 2022-11-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0004_rename_roles_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='roles',
        ),
    ]
