# Generated by Django 4.1.2 on 2022-11-20 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0005_rename_role_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mio_airline_main',
            fields=[
                ('airline_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mio_airline',
            name='airline_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwtapp.mio_airline_main'),
        ),
        migrations.AlterField(
            model_name='user',
            name='airline_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline', to='jwtapp.mio_airline_main'),
        ),
    ]
