# Generated by Django 4.1.2 on 2022-11-25 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0008_alter_mio_flight_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mio_flight_schedule',
            name='time',
            field=models.TimeField(default=datetime.time(21, 4, 42, 69724)),
        ),
    ]
