# Generated by Django 4.1.2 on 2022-12-02 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0012_alter_mio_flight_schedule_baggage_carousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mio_flight_schedule',
            name='gate_close_time',
            field=models.TimeField(default=datetime.time(21, 49, 27, 916149)),
        ),
        migrations.AddField(
            model_name='mio_flight_schedule',
            name='gate_open_time',
            field=models.TimeField(default=datetime.time(21, 59, 27, 916162)),
        ),
        migrations.AlterField(
            model_name='mio_flight_schedule',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 2)),
        ),
        migrations.AlterField(
            model_name='mio_flight_schedule',
            name='time',
            field=models.TimeField(default=datetime.time(21, 54, 27, 916139)),
        ),
        migrations.AlterField(
            model_name='mio_passenger',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 2)),
        ),
    ]
