# Generated by Django 4.1.2 on 2022-12-03 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapp', '0017_alter_mio_flight_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaggageCar',
            fields=[
                ('terminal_carousel', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hour_00', models.CharField(default='open', max_length=10)),
                ('hour_01', models.CharField(default='open', max_length=10)),
                ('hour_02', models.CharField(default='open', max_length=10)),
                ('hour_03', models.CharField(default='open', max_length=10)),
                ('hour_04', models.CharField(default='open', max_length=10)),
                ('hour_05', models.CharField(default='open', max_length=10)),
                ('hour_06', models.CharField(default='open', max_length=10)),
                ('hour_07', models.CharField(default='open', max_length=10)),
                ('hour_08', models.CharField(default='open', max_length=10)),
                ('hour_09', models.CharField(default='open', max_length=10)),
                ('hour_10', models.CharField(default='open', max_length=10)),
                ('hour_11', models.CharField(default='open', max_length=10)),
                ('hour_12', models.CharField(default='open', max_length=10)),
                ('hour_13', models.CharField(default='open', max_length=10)),
                ('hour_14', models.CharField(default='open', max_length=10)),
                ('hour_15', models.CharField(default='open', max_length=10)),
                ('hour_17', models.CharField(default='open', max_length=10)),
                ('hour_18', models.CharField(default='open', max_length=10)),
                ('hour_19', models.CharField(default='open', max_length=10)),
                ('hour_20', models.CharField(default='open', max_length=10)),
                ('hour_21', models.CharField(default='open', max_length=10)),
                ('hour_22', models.CharField(default='open', max_length=10)),
                ('hour_23', models.CharField(default='open', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='mio_flight_schedule',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 3)),
        ),
        migrations.AlterField(
            model_name='mio_flight_schedule',
            name='time',
            field=models.TimeField(default=datetime.time(11, 12, 56, 453230)),
        ),
        migrations.AlterField(
            model_name='mio_passenger',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 3)),
        ),
    ]
